{% set version = "3.0.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gmisc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Gmisc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Gmisc/Gmisc_{{ version }}.tar.gz
  sha256: 83e0f8ab93eedb48e280a786106474dd2ce1dc2df6505835ec4218521e9e0fe9

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'                        # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem            # [win]
    - {{ posix }}make
    - {{ posix }}sed                   # [win]
    - {{ posix }}coreutils             # [win]
    - {{ posix }}zip                   # [win]
    - cross-r-base {{ r_base }}        # [build_platform != target_platform]
  host:
    - r-base
    - r-hmisc
    - r-rcpp >=0.11.4
    - r-xml
    - r-abind
    - r-checkmate
    - r-forestplot
    - r-glue
    - r-htmltable >=2.0.0
    - r-knitr
    - r-lattice
    - r-lubridate
    - r-magrittr
    - r-rlang
    - r-rmarkdown
    - r-stringr
    - r-yaml
  run:
    - r-base
    - r-hmisc
    - r-rcpp >=0.11.4
    - r-xml
    - r-abind
    - r-checkmate
    - r-forestplot
    - r-glue
    - r-htmltable >=2.0.0
    - r-knitr
    - r-lattice
    - r-lubridate
    - r-magrittr
    - r-rlang
    - r-rmarkdown
    - r-stringr
    - r-yaml

test:
  commands:
    - $R -e "library('Gmisc')"           # [not win]
    - "\"%R%\" -e \"library('Gmisc')\""  # [win]

about:
  home: https://gforge.se
  license: GPL-3.0-or-later
  summary: "Tools for making the descriptive \"Table 1\" used in medical articles, a transition plot for showing changes between categories (also known as a Sankey diagram), flow charts by extending the grid package, a method for variable selection based on the SVD, Bézier lines with arrows complementing the ones in the
    'grid' package, and more."
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - leej3

# Package: Gmisc
# Version: 3.0.2
# Title: Descriptive Statistics, Transition Plots, and More
# Author: Max Gordon <max@gforge.se>
# Maintainer: Max Gordon <max@gforge.se>
# Description: Tools for making the descriptive "Table 1" used in medical articles, a transition plot for showing changes between categories (also known as a Sankey diagram), flow charts by extending the grid package, a method for variable selection based on the SVD, Bezier lines with arrows complementing the ones in the 'grid' package, and more.
# License: GPL (>= 3)
# URL: https://gforge.se
# BugReports: https://github.com/gforge/Gmisc/issues
# Biarch: yes
# Depends: R (>= 3.2.0), Rcpp (>= 0.11.4), htmlTable (>= 2.0.0)
# Imports: abind, checkmate, forestplot, Hmisc, glue, grid, grDevices, graphics, knitr, lattice, lubridate, magrittr, methods, rlang, rmarkdown, stringr, stats, XML, yaml, utils
# Suggests: datasets, dplyr, jsonlite, testthat, tidyselect
# Encoding: UTF-8
# NeedsCompilation: yes
# VignetteBuilder: knitr
# LinkingTo: Rcpp
# RoxygenNote: 7.2.2
# Packaged: 2023-03-13 12:52:07 UTC; max
# Repository: CRAN
# Date/Publication: 2023-03-13 17:10:27 UTC
